[colors.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#1e2327"
foreground = "#d3c6aa"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 13

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

#[font.monospace]
#family = "JetBrainsMono NFM"
#style = "Regular"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
action = "PasteSelection"
key = "P"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "CopySelection"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Search"
mods = "Super"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Super|Control"

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
opacity = 0.95

[window.dimensions]
columns = 106
lines = 40

[window.padding]
x = 0
y = 0
