require('config.colorscheme')
require('config.telescope')
require('config.nvim-cmp')
require('config.treesitter')
require('config.devicon')
require('config.autopairs')
require('config.lualine')
--
-- require('config.trouble')
-- require('config.fugitive')
-- require('config.neogit')
-- require('config.project')
-- require('config.lspkind')
-- require('config.lir')
-- require('config.colorizer')
-- require('config.lightbulb')
-- require('config.snippets')
-- require('config.completion')
-- require('config.slime')
