[flags]
group_processes = false
color = "gruvbox"
mem_as_value = true
tree = false

[[row]]
  ratio=1
  [[row.child]]
    type="cpu"
[[row]]
  ratio=2
  [[row.child]]
    type="proc"
    default=true
