#!/usr/bin/env bash

function toggle {
    bt_hs=$(eww get bt_headset)
    name=$(echo $bt_hs | jq -r '.name')
    profile=$(echo $bt_hs | jq -r '.profile')
    if [[ $profile == 'a2dp-sink' ]]; 
    then 
        pactl set-card-profile $name headset-head-unit-msbc
    else 
        pactl set-card-profile $name a2dp-sink
    fi
    eww update bt_headset="$(pactl --format=json list cards | jq 'last | { name: .name, profile: .active_profile}')"
}

if [[ $1 == 'toggle' ]]; then toggle; fi
