---
session:
  name: "zapp" # a string, that names the session
  attach: true # default `true`. If session exists, re-attach.

template:
  direction: Horizontal
  parts:
    - direction: Vertical
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:compact-bar"
      borderless: true
    - direction: Vertical
      body: true
        #    - direction: Vertical
        #      split_size:
        #        Fixed: 2
        #      run:
        #        plugin:
        #          location: "zellij:status-bar"
        #      borderless: true

tabs:
  - name: "code" 
    direction: Vertical
    run:
      command: { cmd: zsh, args: ["-c", "cd ~/code && zsh"] }
  - name: "zsh" 
    direction: Vertical
    parts:
    - direction: Vertical
      split_size:
        Percent: 50
      run:
        command: { cmd: zsh, args: ["-c", "cd ~/.config && zsh"] }
    - direction: Vertical
      split_size:
        Percent: 50
  - name: "bottom" 
    direction: Vertical
    run:
      command: {cmd: btm}
    focus: true
