
vim.keymap.set('n', '<Esc>', '<cmd>noh<CR>:cclose<CR><Esc>', {silent=true})
vim.keymap.set('n', 'k', 'gk')
vim.keymap.set('n', 'j', 'gj')
vim.keymap.set('n', '<SPACE>', '<nop>')
vim.keymap.set('n', '<up>', '<nop>')
vim.keymap.set('n', '<down>', '<nop>')
vim.keymap.set('n', '<left>', '<nop>')
vim.keymap.set('n', '<right>', '<nop>')
vim.keymap.set('i', '<up>', '<nop>')
vim.keymap.set('i', '<down>', '<nop>')
vim.keymap.set('i', '<left>', '<nop>')
vim.keymap.set('i', '<right>', '<nop>')
vim.keymap.set('t', '<Esc>', '<C-\\><C-n>')

-- Lsp
vim.keymap.set('n', '<leader>ru', '<cmd>RustRunnables<CR>')
vim.keymap.set('n', '<F1>',       vim.lsp.buf.formatting)
vim.keymap.set('n', '<F2>',       vim.lsp.buf.rename)
vim.keymap.set('n', 'gd',         vim.lsp.buf.definition)
vim.keymap.set('n', 'gt',         vim.lsp.buf.type_definition)
vim.keymap.set('n', '<leader>a',  vim.lsp.buf.code_action)
vim.keymap.set('n', '<leader>aa', vim.lsp.buf.range_code_action)
vim.keymap.set('n', '<leader>h',  vim.lsp.buf.hover)
vim.keymap.set('n', '<leader>dn', vim.diagnostic.goto_next)
vim.keymap.set('n', '<leader>dp', vim.diagnostic.goto_prev)
vim.keymap.set('n', '<leader>dd', function() vim.diagnostic.open_float(nil, {scope = "line"}) end)

-- Telescope
local telescope = require'telescope.builtin'
vim.keymap.set('n', '<leader>ff', telescope.find_files)
vim.keymap.set('n', '<leader>fg', telescope.git_files)
vim.keymap.set('n', '<leader>rg', telescope.live_grep)
vim.keymap.set('n', '<leader>b',  telescope.buffers)
vim.keymap.set('n', '<leader>re', telescope.lsp_references)
vim.keymap.set('n', '<leader>sy', telescope.lsp_document_symbols)
vim.keymap.set('n', '<leader>q',  telescope.diagnostics)

vim.cmd(':command! WQ wq')
vim.cmd(':command! WQ wq')
vim.cmd(':command! Wq wq')
vim.cmd(':command! Wqa wqa')
vim.cmd(':command! W w')
vim.cmd(':command! Q q')          
